### PR TITLE
Add ESLint to CI

### LINKED ISSUE #17: Add ESLint to CI
Fail if not conforming

### PR DESCRIPTION
**Pull request by daveshah**
WIP, but definitely fishin' for feedback 🐟

Closes #17

### CODE REVIEW

**Comment by austenmadden** [comment]
@daveshah One thing I noticed while I was watching you push up these changes is that the linter failed the build. Is that a desirable trait? I imagine so, but would be open to opinions on that.

**Comment by daveshah** [comment]
I personally think that's a desirable trait. I'd prefer if the linter failed the build to keep the codebase consistent. That said, I also like the idea of keeping the config simple and leaving the defaults on (Graham sold me on this a while back and I agree with his sentiment that it helps to avoid bike shedding :) )

**Review by austenmadden — APPROVED** [review]
LGTM 🐠

**Comment by conzett** [comment]
👍  for linter failing build + using linter defaults.

**Review by conzett — DISMISSED** [review]
LGTM pending squash!

**Review by conzett — APPROVED** [review]
Good call on adding to the README. Looks good 👍

**Pull request merged**
