### PR TITLE
Upgrade react-scripts and storybook

### PR DESCRIPTION
**Pull request by nlegg**
Should address #16. Storybook had to be upgraded too, or else [move it to the bottom of `devDependencies`](https://github.com/facebookincubator/create-react-app/issues/2352).

### CODE REVIEW

**Comment by conzett** [comment]
Couple of questions:
- Is there anything that we need to run post-update to update other things? Webpack config etc?
- Do we still see the need for the storybook stuff now that we have a fixture and demo app setup?

**Comment by nlegg** [comment]
I did not have to run anything after the upgrade steps; `yarn start` boots up just fine for me.

**Comment by conzett** [comment]
@daveshah - any objections to removing the storybook stuff if we're not using it (not sure if we are or not)?

**Comment by daveshah** [comment]
@conzett regarding storybooks:
The idea that I had around these was that we would definitely check them in and use them for our individual components. I thought It'd be cool if Megalodoc was also able to serve as a library for OpenAPI documentation 'components' that people could pick and choose if they wanted to customize the way their documentation looked (instead of rolling with the default Megalodoc setup). That said, storybooks would serve as a way to view individual components to help in the picking and choosing what they wanted. 

I'd like to keep them in if we'd like to go that route to experiment with that idea, but if that's not something we might want to do longterm, or they're getting in the way of anything, I'm not opposed to removing them.

**Review by conzett — CHANGES_REQUESTED** [review]
Approved pending rebase and commit message tweaks 👍

**Comment by nlegg** [comment]
Rebased and re-commit-messaged 👍

**Review by conzett — APPROVED** [review]
👍 👍

**Pull request merged**
